apiVersion: v1
kind: Service
metadata:
  name: framer-site-service
  namespace: framer-site
spec:
  internalTrafficPolicy: Cluster
  selector:
    app: framer-site
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
