apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: framer-site
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/smolinari/framer' 
    targetRevision: HEAD
    path: .m8a/deployments/framer-site
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: framer-site
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true